### ISSUE TITLE
玩家可以使用远程武器伤害受保护的实体

### ISSUE THREAD

**Issue by GreyElaina** [teaconmc/AreaControl#1]
远程武器示例:
 - `WaterSparyer` 中的物品 `熔岩喷雾瓶`
 - 原版 Minecraft 中的弓

**Comment by 3TUSK** [comment]
实际上物品展示框依旧可以被弓打下来……

**Comment by 3TUSK** [comment]
`LivingAttackEvent` will only be fired for living entities (`instanceof LivingEntity`). For non-living entities such as item frame, minecart, boat, … nothing we can do. … Even though we should have been able to do something?

**Comment by GreyElaina** [comment]
its finally gone.
